extends:
  import: classic
  file: pipeline.yaml
agent:
  label: jenkins-maven
  container: maven
pipelines:
  pullRequest:
    build:
      steps:
        - sh: skaffold version
          name: skaffold-version
        - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
          name: container-build

  release:
    setVersion:
      steps:
       - sh: echo \$(jx-release-version) > VERSION
       - sh: jx step tag --version \$(cat VERSION)
       - sh: echo $DOCKER_REGISTRY_ORG > APP_NAME
       - sh: export VERSION=`cat VERSION` && export CLIENT_NAME=`cat APP_NAME` && skaffold build -f skaffold.yaml
    build:
      steps:
       - sh: jx step post build --image $DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:\$(cat VERSION)
         name: container-build
    promote:
      steps:
      - sh: jx step changelog --version v\$(cat VERSION)
        name: changelog
      - dir: charts/REPLACE_ME_APP_NAME
        steps:
        - comment: release the helm chart
          sh: jx step helm release
      - comment: promote through all 'Auto' promotion Environments
        sh: jx promote -b --all-auto --timeout 1h --version \$(cat VERSION)
