# Default values for liferay.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: marrih/naseejmedad
  tag: client10
  pullPolicy: Always


dbname: mddl-client10

clientname: ""
cleintConfig:
  MEDAD_DL_CLIENT_DSPACE_URL: ""
  MEDAD_DSPACE_REST_URL: ""
  MEDAD_DSPACE_COMMUNITY: ""
  MEDAD_SUBJECT_GROUP_COMM_ID: ""
  MEDAD_TYPE_GROUP_COMM_ID: ""
  MEDAD_DL_CLIENT_GOOGLE_ANALYTICS_ID: ""
  
  MEDAD_DL_CLIENT_GOOGLE_ANALYTICS_EMAIL: ""
  MEDAD_DL_CLIENT_GOOGLE_ANALYTICS_NAME: ""
  MEDAD_DL_CLIENT_MAIL_ID: ""
  MEDAD_DL_CLIENT_MAIL_FROM_EMAIL: ""
  MEDAD_DL_CLIENT_MAIL_SERVICE_NAME: ""

medadplugins: ""
artifacthost: "http://nexus.jx.35.166.225.194.nip.io"
artifactrepo: ""
artifactorygroup: ""


imagePullSecrets:
  - name:  aws-registry
nameOverride: ""
fullnameOverride: ""

service:
  port: 8080
  type: ClusterIP

ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: nginx
     ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: 35.166.225.194.nip.io


  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
     memory: 3Gi
  requests:
     memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
