apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: local-config-map
  namespace: {{ .Release.Namespace }}
data:
  tomcat-users.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <tomcat-users xmlns="http://tomcat.apache.org/xml"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
              version="1.0">
              <role rolename="manager-gui"/>
              <user username="admin" password="admin" roles="manager-gui"/>
              <role rolename="admin-gui"/>
              <user username="tomcat" password="s3cret" roles="admin-gui"/>
    </tomcat-users>
  local.cfg: |-
    dspace.dir = /dspace
    db.url = {{ .Values.dbhost }}.{{ .Values.dbname }}
    dspace.hostname = ds.{{ .Release.Namespace }}.{{ .host }}
    dspace.baseUrl = http://ds.{{ .Release.Namespace }}.{{ .host }}:8080
    solr.server=http://ds.{{ .Release.Namespace }}.{{ .host }}:8080/solr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dspace.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: dspace-app
{{ include "dspace.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dspace.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: dspace-app
  strategy:
     type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "dspace.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: dspace-app
    spec:
      containers:
        - env:
          - name: MEDAD_DSPACE_URL
            value: {{ .MEDAD_DSPACE_URL }}
          - name: MEDAD_DSPACE_URL_EMAIL
            value: {{ .MEDAD_DSPACE_URL_EMAIL }}
          - name: MEDAD_DSPACE_URL_PASSWORD
            value: {{ .MEDAD_DSPACE_URL_PASSWORD }}
          - name: MEDAD_DSPACE_URL_COMM
            value: {{ .MEDAD_DSPACE_URL_COMM }}
          - name: DSPACE_MEDAD_COMMUNITY
            value: {{ .DSPACE_MEDAD_COMMUNITY }}
          - name: MEDAD_DSPACE_URL_OAUTH_SECRET
            value: {{ .MEDAD_DSPACE_URL_OAUTH_SECRET }}
      - image:  {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: dspace
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: "/dspace/assetstore"
          name: "assetstore"
        - mountPath: "/usr/local/tomcat/conf/tomcat-users.xml"
          name: "my-local-config-map"
          subPath: tomcat-users.xml
        - mountPath: "/dspace/config/local.cfg"
          name: "my-local-config-map"
          subPath: local.cfg
        - name: "solr-authority"
          mountPath: "/opt/solr/server/solr/authority/data"
        - name: "solr-oai"
          mountPath: "/opt/solr/server/solr/oai/data"
        - name: "solr-search"
          mountPath: "/opt/solr/server/solr/search/data"
        - name: "solr-statistics"
          mountPath: "/opt/solr/server/solr/statistics/data"
        readinessProbe:
          httpGet:
            path: /xmlui/contact
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
        livenessProbe:
          httpGet:
            path: /xmlui/contact
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 5
          periodSeconds: 120
        command: ['sh', '-c', '/dspace/bin/dspace database migrate; catalina.sh run']
      volumes:
      - name: "assetstore"
        hostPath:
          path: "/tmp/vols/assetstore"
      - name: my-local-config-map
        configMap:
          name: local-config-map
      - name: "solr-authority"
        hostPath:
          path: "/tmp/vols/solr-authority"
      - name: "solr-oai"
        hostPath:
          path: "/tmp/vols/solr-oai"
      - name: "solr-search"
        hostPath:
          path: "/tmp/vols/solr-search"
      - name: "solr-statistics"
        hostPath:
          path: "/tmp/vols/solr-statistics"
        {{- with .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.imagePullSecrets }}
        imagePullSecrets:
         {{- toYaml . | nindent 8 }}
       {{- end }}