# Default values for liferay.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: Always

clientname: clientx-stg
dbname: dspace_client01_stg
dbhost: jdbc:postgresql://postgres.liferay:5432/
imagePullSecrets:
  - name:  aws-registry
nameOverride: ""
fullnameOverride: ""

clientconfig:
  MEDAD_DSPACE_URL =http://dspace.md-client01-stg.35.166.225.194.nip.io/
  MEDAD_DSPACE_URL_EMAIL = ahmed.abdelsalam@naseej.com
  MEDAD_DSPACE_URL_PASSWORD =AAS@ADMIN
  MEDAD_DSPACE_URL_COMM = 992311a1-20b1-4bc8-9255-e79cd2f10d68
  DSPACE_MEDAD_COMMUNITY = 992311a1-20b1-4bc8-9255-e79cd2f10d68
  MEDAD_DSPACE_URL_OAUTH_SECRET= secret

service:
  port: 8080
  type: ClusterIP

ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: nginx
     ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: 35.166.225.194.nip.io


  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
     memory: 3Gi
  requests:
     memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
