apiVersion: v1
kind: Service
metadata:
  name: {{ include "md-container-rest.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "md-container-rest.labels" . | indent 4 }}
spec:
  ports:
  - name: "6060"  
    port: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "md-container-rest.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
